### ISSUE TITLE
Update fitur.

### ISSUE THREAD

**Issue by miezlearning** [aldinh777/cheat-sia#1]
nanti ada aplikasi SIA baru bang namnaya AIS, nnti diupdate yak bang

**Comment by uxdiin** [comment]
kau update sendiri lah

**Comment by dutaibnu** [comment]
> kau update sendiri lah

jagoan kah kamu, ngasi tau itu baik baik bro, namanya repo orang ya ga salah lah dia minta update

**Comment by miezlearning** [comment]
> kau update sendiri lah

siap abangkuu

**Comment by miezlearning** [comment]
> > kau update sendiri lah
> 
> jagoan kah kamu, ngasi tau itu baik baik bro, namanya repo orang ya ga salah lah dia minta update

aman bang, biarin aja

**Comment by aldinh777** [comment]
> nanti ada aplikasi SIA baru bang namnaya AIS, nnti diupdate yak bang

saya gak bisa buatin juga karena gak punya akun AIS, jadi gak ada bahan buat testing di web nya.
yang kamu buat juga udah mantep banget tuh [Cheat AIS](https://github.com/miezlearning/cheat-ais).
makasih juga yak udah masukin credit nya hehe
